name: TinyGo Bluepill Build CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - uses: acifani/setup-tinygo@v2
        with:
        tinygo-version: '0.30.0'

      - name: Install Qrepo
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/nthnn/Qrepo/master/support/install.sh)"

      - name: Go version
        run: go version

      - name: Run test suites
        run: qrepo run build
